version: '2'


services:
  web:
    build:
      context: .
      dockerfile: Dockerfile1
    container_name: web
    ports:
      - "34000:6000"
  log:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log0
    ports:
      - "34001:6000"
  log1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log1
    ports:
      - "34002:6000"
  log2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log2
    ports:
      - "34003:6000"
  db:
    image: mongo:3.6.1
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - "30000:27017"
    command: mongod

volumes:
  mongodb:
  mongodb_config: